DECLARE num NUMBER;
BEGIN
SELECT COUNT(1) INTO num FROM USER_TABLES WHERE TABLE_NAME = UPPER('TB_COMPONENT') ;
IF num > 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE TB_COMPONENT' ;
END IF;
END;
/

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM ALL_SEQUENCES
  WHERE SEQUENCE_NAME = 'SEQ_TB_COMPONENT_ID';
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TB_COMPONENT_ID';
END IF;
END
;
/
CREATE TABLE TB_COMPONENT
(
	id NUMBER(38) NOT NULL,
	parent_id NUMBER(38) DEFAULT 0 NOT NULL,    -- 父组件ID
	cuid VARCHAR2(32) NOT NULL,    -- 组件唯一标识
	name VARCHAR2(50) NOT NULL,    -- 组件名称
	type NUMBER(10) NOT NULL,    -- 组件类型：1 菜单  2 权限要素
	sort NUMBER DEFAULT 0 NOT NULL,
	enable NUMBER(10) DEFAULT 1 NOT NULL,    -- 是否可用 1 可用 0 不可用
	term_type VARCHAR2(50),    -- 终端类型 1-IOS 2-Android 3-Web 多个用逗号隔开
	url VARCHAR2(256),    -- 菜单URL
	add_time NUMBER(13) NOT NULL,    -- 添加时间
  "COMMENT" VARCHAR2(500)    -- 备注
);

COMMENT ON TABLE TB_COMPONENT IS '组件表'
;

COMMENT ON COLUMN TB_COMPONENT.parent_id IS '父组件ID'
;

COMMENT ON COLUMN TB_COMPONENT.cuid IS '组件唯一标识'
;

COMMENT ON COLUMN TB_COMPONENT.name IS '组件名称'
;

COMMENT ON COLUMN TB_COMPONENT.type IS '组件类型：1 菜单  2 权限要素'
;

COMMENT ON COLUMN TB_COMPONENT.enable IS '是否可用 1 可用 0 不可用'
;

COMMENT ON COLUMN TB_COMPONENT.term_type IS '终端类型 1-IOS 2-Android 3-Web 多个用逗号隔开'
;

COMMENT ON COLUMN TB_COMPONENT.url IS '菜单URL'
;

COMMENT ON COLUMN TB_COMPONENT.add_time IS '添加时间'
;

COMMENT ON COLUMN TB_COMPONENT."COMMENT" IS '备注'
;

ALTER TABLE TB_COMPONENT
 ADD CONSTRAINT PK_TB_COMPONENT
  PRIMARY KEY (id) USING INDEX
;

CREATE SEQUENCE SEQ_TB_COMPONENT_ID
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE  1
  NOCYCLE
  NOCACHE
  NOORDER
;
CREATE OR REPLACE TRIGGER TRG_TB_COMPONENT_ID
  BEFORE INSERT
  ON TB_COMPONENT
  FOR EACH ROW
  BEGIN
    SELECT SEQ_TB_COMPONENT_ID.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
  END;
