DECLARE num NUMBER;
BEGIN
SELECT COUNT(1) INTO num FROM USER_TABLES WHERE TABLE_NAME = UPPER('TB_ROLE') ;
IF num > 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE TB_ROLE' ;
END IF;
END;
/

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM ALL_SEQUENCES
  WHERE SEQUENCE_NAME = 'SEQ_TB_ROLE_ID';
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TB_ROLE_ID';
END IF;
END
;
/
CREATE TABLE TB_ROLE
(
	id NUMBER(38) NOT NULL,    -- 角色ID
	name VARCHAR2(50) NOT NULL,    -- 角色名称
	is_def NUMBER(10) DEFAULT 0 NOT NULL,    -- 是否默认 1 是 0 否
	"COMMENT" VARCHAR2(500),    -- 角色备注
	add_time NUMBER(13) NOT NULL    -- 添加时间
);

COMMENT ON TABLE TB_ROLE IS '角色表'
;

COMMENT ON COLUMN TB_ROLE.id IS '角色ID'
;

COMMENT ON COLUMN TB_ROLE.name IS '角色名称'
;

COMMENT ON COLUMN TB_ROLE.is_def IS '是否默认 1 是 0 否'
;

COMMENT ON COLUMN TB_ROLE."COMMENT" IS '角色备注'
;

COMMENT ON COLUMN TB_ROLE.add_time IS '添加时间'
;

ALTER TABLE TB_ROLE 
 ADD CONSTRAINT PK_TB_ROLE
	PRIMARY KEY (id) USING INDEX
;

CREATE SEQUENCE SEQ_TB_ROLE_ID
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;

CREATE OR REPLACE TRIGGER TRG_TB_ROLE_ID
	BEFORE INSERT ON TB_ROLE
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_TB_ROLE_ID.NEXTVAL 
		INTO :NEW.ID
		FROM DUAL; 
	END;
