DECLARE num NUMBER;
BEGIN
SELECT COUNT(1) INTO num FROM USER_TABLES WHERE TABLE_NAME = UPPER('TB_USER') ;
IF num > 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE TB_USER' ;
END IF;
END;
/

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM ALL_SEQUENCES
  WHERE SEQUENCE_NAME = 'SEQ_TB_USER_ID';
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TB_USER_ID';
END IF;
END
;
/
CREATE TABLE TB_USER
(
  id NUMBER(38),    -- 用户ID
  user_num VARCHAR2(20) NOT NULL,    -- 用户编号，客户号或者员工号
  user_name VARCHAR2(50) NOT NULL,
  user_attr VARCHAR2(1000),    -- 用户属性，JSON格式
  add_time NUMBER(13) NOT NULL    -- 添加时间
);

COMMENT ON COLUMN TB_USER.id IS '用户ID'
;

COMMENT ON COLUMN TB_USER.user_num IS '用户编号，客户号或者员工号'
;

COMMENT ON COLUMN TB_USER.user_attr IS '用户属性，JSON格式'
;

COMMENT ON COLUMN TB_USER.add_time IS '添加时间'
;

ALTER TABLE TB_USER
 ADD CONSTRAINT PK_TB_USER
  PRIMARY KEY (id) USING INDEX
;

CREATE SEQUENCE SEQ_TB_USER_ID
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE  1
  NOCYCLE
  NOCACHE
  NOORDER
;

create or replace trigger TRG_TB_USER_ID
  before insert on TB_USER
  for each row
declare
  -- local variables here
begin
  SELECT SEQ_TB_USER_ID.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
end TRG_TB_USER_ID;



