spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?charsetEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true

    #hibernante ddl
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
