application:
  #应用名称：当使用到微服务配置中心时，name必须和对应应用匹配
  name: ams_server_demo

server:
  display-name: webTemplate
  port: 8080
  servlet-path: /           #context,默认/
  session:
    timeout: 1800           #会话超时时间,秒
    cookie:
      http-only: true
      name: mySession       #当不使用springSession时，用此区分不同系统的sessionCookieName，启用springSession此参数不生效

spring:
  datasource:
    mainDs:
      name: main-mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.3.28:3306/monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: monitor
      password: ENC(347C69CBC6D3AEDA320F5B5707543D15)
      initialSize: 5
      maxActive: 20
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      filters: stat,wall
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10
      max-request-size: 10

  session:
    store-type: redis
    redis:
      namespace: wt       #使用SpringSession，若存在多系统共用redis的情况，namespace必须区分开来

  redis:
    database: 0
    host: 192.168.3.136
    port: 6379
    password: ENC(1083061FF4033F3397FED9C2AF4AED9F)
    pool:
      max-active: 100
      max-idle: 5
      max-wait: 60000
