DECLARE num NUMBER;
BEGIN
SELECT COUNT(1) INTO num FROM USER_TABLES WHERE TABLE_NAME = UPPER('TB_CLIENT_SETTING') ;
IF num > 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE TB_CLIENT_SETTING' ;
END IF;
END;
/

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM ALL_SEQUENCES
  WHERE SEQUENCE_NAME = 'SEQ_TB_CLIENT_SETTING_ID';
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TB_CLIENT_SETTING_ID';
END IF;
END
;
/
CREATE TABLE TB_CLIENT_SETTING
(
  id NUMBER(38) NOT NULL,
  client_id VARCHAR2(64),
  name VARCHAR2(64),
  secret VARCHAR2(255),
  remark VARCHAR2(255),
  status VARCHAR2(10) DEFAULT '0',
  add_time NUMBER(38),
  ext CLOB
);



COMMENT ON TABLE TB_CLIENT_SETTING IS '客户端设置表'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.client_id IS '客户端ID'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.name IS '客户端名称'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.secret IS '秘钥'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.remark IS '备注'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.status IS '状态，1:启用，0:停用'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.add_time IS '添加时间'
;

COMMENT ON COLUMN TB_CLIENT_SETTING.ext IS '参数配置'
;

ALTER TABLE TB_CLIENT_SETTING
 ADD CONSTRAINT PK_TB_CLIENT_SETTING
	PRIMARY KEY (id) USING INDEX
;

CREATE SEQUENCE SEQ_TB_CLIENT_SETTING_ID
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE  1
	NOCYCLE
	NOCACHE
	NOORDER
;
CREATE OR REPLACE TRIGGER TRG_TB_CLIENT_SETTING_ID
	BEFORE INSERT
	ON tb_client_setting
	FOR EACH ROW
	BEGIN
		SELECT SEQ_TB_CLIENT_SETTING_ID.NEXTVAL
		INTO :NEW.ID
		FROM DUAL;
	END;