DECLARE num NUMBER;
BEGIN
SELECT COUNT(1) INTO num FROM USER_TABLES WHERE TABLE_NAME = UPPER('TB_PUSH_TERMINAL') ;
IF num > 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE TB_PUSH_TERMINAL' ;
END IF;
END;
/

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM ALL_SEQUENCES
  WHERE SEQUENCE_NAME = 'SEQ_TB_PUSH_TERMINAL_ID';
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TB_PUSH_TERMINAL_ID';
END IF;
END
;
/
CREATE TABLE TB_PUSH_TERMINAL
(
  id number(38) NOT NULL ,
  platform VARCHAR2(50) NOT NULL,
  token VARCHAR2(200) NOT NULL,
  tag VARCHAR2(200),
  alias VARCHAR2(50),
  badge number(10) default 0 ,
  add_time number(13),
  modify_time  number(13)
);

COMMENT ON TABLE TB_PUSH_TERMINAL IS '推送终端表'
;

COMMENT ON COLUMN TB_PUSH_TERMINAL.platform IS '平台：ios、android'
;
COMMENT ON COLUMN TB_PUSH_TERMINAL.token IS '机器码'
;
COMMENT ON COLUMN TB_PUSH_TERMINAL.tag IS '标签'
;
COMMENT ON COLUMN TB_PUSH_TERMINAL.alias IS '别名'
;
COMMENT ON COLUMN TB_PUSH_TERMINAL.badge IS '未读消息数'
;
COMMENT ON COLUMN TB_PUSH_TERMINAL.add_time IS '创建时间'
;
COMMENT ON COLUMN TB_PUSH_TERMINAL.modify_time IS '修改时间'
;

ALTER TABLE TB_PUSH_TERMINAL
 ADD CONSTRAINT PK_TB_PUSH_TERMINAL
  PRIMARY KEY (id) USING INDEX
;

CREATE SEQUENCE SEQ_TB_PUSH_TERMINAL_ID
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE  1
  NOCYCLE
  NOCACHE
  NOORDER
;

CREATE OR REPLACE TRIGGER TRG_TB_PUSH_TERMINAL_ID
  BEFORE INSERT
  ON TB_PUSH_TERMINAL
  FOR EACH ROW
  BEGIN
    SELECT SEQ_TB_PUSH_TERMINAL_ID.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
  END;